### ISSUE TITLE
The script stores empty values ​​in the database.

### ISSUE THREAD

**Issue by getmac777** [azutake/az-stancekit#1]
Hello. Sorry for my English. I will try to explain as correctly as possible: I use az-stancekit and JonasDev17/qb-garages. I noticed that az-stancer stores empty values ​​in the database. The script does not produce any errors related to oxmysql and so on.

![image](https://github.com/azutake/az-stancekit/assets/140545358/983e00ea-d143-490e-8167-e1a8c8d877b5)

**Comment by azutake** [comment]
@getmac777 Thank you for open issue!
Can I ask you to verify the following items?
- Is the server running on OneSync?
- If you are using `SetRoutingBucketEntityLockdownMode`, make sure it is not strict.
- With multiple people in the same location, is the appearance of the stance reflected to the others?
  - (If not, there is most likely something wrong with the OneSync sync. Try increasing the game build version if possible)

**Comment by getmac777** [comment]
Thank you very much for your answer. 

1. server running on OneSync

2. Unfortunately, I don’t know what we’re talking about) That is, perhaps one of the scripts uses this native and breaks az-stancerkit?

**Comment by getmac777** [comment]
"If you are using SetRoutingBucketEntityLockdownMode, make sure it is not strict."

Can you please tell me where I can change this? Or should I look at all the scripts used?

**Comment by getmac777** [comment]
Another addition: I checked my entire repository and did not find the “SetRoutingBucketEntityLockdownMode” line in the code. So that's probably not the issue...

**Comment by getmac777** [comment]
Sorry to bother you. I have fixed the problem. 

Never disable automatic game updates in EGS)))

**Comment by azutake** [comment]
Sorry! I was away on Saturday and Sunday.
I'm glad you got it resolved :)
